apiVersion: v1
kind: Service
metadata:
  name: book-catalog-lb-service
  namespace: anz-name-space
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8070
  selector:
    app: book-catalog
